// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3uYecf3FBdVzsQC1ipQK5Hcjpnd3M-E',
    appId: '1:668749596101:web:964b52e5e4f83f8f6a77ac',
    messagingSenderId: '668749596101',
    projectId: 'chat-app-1ca15',
    authDomain: 'chat-app-1ca15.firebaseapp.com',
    databaseURL: 'https://chat-app-1ca15-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-1ca15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3uYecf3FBdVzsQC1ipQK5Hcjpnd3M-E',
    appId: '1:668749596101:android:964b52e5e4f83f8f6a77ac',
    messagingSenderId: '668749596101',
    projectId: 'chat-app-1ca15',
    databaseURL: 'https://chat-app-1ca15-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-1ca15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD3uYecf3FBdVzsQC1ipQK5Hcjpnd3M-E',
    appId: '1:668749596101:ios:964b52e5e4f83f8f6a77ac',
    messagingSenderId: '668749596101',
    projectId: 'chat-app-1ca15',
    databaseURL: 'https://chat-app-1ca15-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-1ca15.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD3uYecf3FBdVzsQC1ipQK5Hcjpnd3M-E',
    appId: '1:668749596101:ios:964b52e5e4f83f8f6a77ac',
    messagingSenderId: '668749596101',
    projectId: 'chat-app-1ca15',
    databaseURL: 'https://chat-app-1ca15-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-1ca15.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3uYecf3FBdVzsQC1ipQK5Hcjpnd3M-E',
    appId: '1:668749596101:web:964b52e5e4f83f8f6a77ac',
    messagingSenderId: '668749596101',
    projectId: 'chat-app-1ca15',
    authDomain: 'chat-app-1ca15.firebaseapp.com',
    databaseURL: 'https://chat-app-1ca15-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-1ca15.firebasestorage.app',
  );
}
